import React from 'react'

const ContentRights = () => {
  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-4xl mx-auto p-6 bg-white rounded-lg shadow-sm">
        <h1 className="text-3xl font-bold text-gray-900 mb-6">Content Rights Information for Mosaic AI Story Maker</h1>
        <p className="text-sm text-gray-600 mb-8">Last Updated: September 2025</p>
        
        <div className="prose prose-lg max-w-none">
          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b border-gray-200 pb-2">Content Rights Overview</h2>
          <p className="mb-6 text-black leading-relaxed">
            Mosaic AI Story Maker respects intellectual property rights and is committed to protecting the rights of content creators, users, and third parties. This document outlines our content rights policies and procedures.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b border-gray-200 pb-2">Content Categories</h2>
          
          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">1. Original App Content</h3>
          <p className="mb-2 text-black"><strong>Rights Holder</strong>: Mosaic AI Story Maker</p>
          <p className="mb-2 text-black"><strong>Content Includes</strong>:</p>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">App source code and software architecture</li>
            <li className="mb-1">User interface design and visual elements</li>
            <li className="mb-1">App icons, logos, and branding materials</li>
            <li className="mb-1">Original character designs and illustrations</li>
            <li className="mb-1">Story templates and AI prompts</li>
            <li className="mb-1">Database schemas and API structures</li>
          </ul>
          <p className="mb-4 text-black"><strong>Rights</strong>: All rights reserved. Protected by copyright and trademark laws.</p>

          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">2. AI-Generated Content</h3>
          <p className="mb-2 text-black"><strong>Rights Holder</strong>: Mosaic AI Story Maker (technology) / Users (personal use)</p>
          <p className="mb-2 text-black"><strong>Content Includes</strong>:</p>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Stories generated by our AI algorithms</li>
            <li className="mb-1">Audio narrations created from text</li>
            <li className="mb-1">Personalized story elements based on user input</li>
            <li className="mb-1">Character descriptions and story themes</li>
          </ul>
          <p className="mb-2 text-black"><strong>Rights</strong>:</p>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Users receive a limited license for personal use</li>
            <li className="mb-1">Commercial use requires written permission</li>
            <li className="mb-1">We retain rights to the underlying AI technology</li>
          </ul>

          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">3. User-Generated Content</h3>
          <p className="mb-2 text-black"><strong>Rights Holder</strong>: Users</p>
          <p className="mb-2 text-black"><strong>Content Includes</strong>:</p>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Personal information and preferences</li>
            <li className="mb-1">Story customization choices</li>
            <li className="mb-1">User-created character descriptions</li>
            <li className="mb-1">Personal story collections</li>
          </ul>
          <p className="mb-4 text-black"><strong>Rights</strong>: Users retain ownership with limited license to us for service provision.</p>

          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">4. Third-Party Content</h3>
          <p className="mb-2 text-black"><strong>Rights Holder</strong>: Respective third-party owners</p>
          <p className="mb-2 text-black"><strong>Content Includes</strong>:</p>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Open source software components</li>
            <li className="mb-1">Third-party service integrations</li>
            <li className="mb-1">Licensed fonts and visual assets</li>
            <li className="mb-1">API services and data</li>
          </ul>
          <p className="mb-4 text-black"><strong>Rights</strong>: Governed by respective third-party licenses and terms of service.</p>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b border-gray-200 pb-2">Content Usage Rights</h2>
          
          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">User Rights</h3>
          <p className="mb-2 text-black"><strong>Personal Use License</strong>:</p>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Create unlimited personalized stories for personal use</li>
            <li className="mb-1">Share stories with family and friends</li>
            <li className="mb-1">Access and modify personal story collections</li>
            <li className="mb-1">Use premium features with valid subscription</li>
          </ul>
          <p className="mb-2 text-black"><strong>Restrictions</strong>:</p>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">No commercial distribution of AI-generated content</li>
            <li className="mb-1">No resale or licensing of generated stories</li>
            <li className="mb-1">No reverse engineering of AI algorithms</li>
            <li className="mb-1">No unauthorized sharing of account access</li>
          </ul>

          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">App Rights</h3>
          <p className="mb-2 text-black"><strong>Service Provision License</strong>:</p>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Use user data to provide personalized services</li>
            <li className="mb-1">Generate and store stories based on user preferences</li>
            <li className="mb-1">Analyze usage patterns to improve the service</li>
            <li className="mb-1">Create aggregated, anonymized analytics</li>
          </ul>
          <p className="mb-2 text-black"><strong>Content Moderation Rights</strong>:</p>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Review content for inappropriate material</li>
            <li className="mb-1">Remove or modify content that violates terms</li>
            <li className="mb-1">Suspend accounts for policy violations</li>
            <li className="mb-1">Implement content filtering and safety measures</li>
          </ul>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b border-gray-200 pb-2">Content Moderation</h2>
          
          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Prohibited Content</h3>
          <p className="mb-2 text-black">We reserve the right to remove or reject content that:</p>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Contains inappropriate or offensive material</li>
            <li className="mb-1">Promotes violence, discrimination, or illegal activities</li>
            <li className="mb-1">Infringes on third-party intellectual property rights</li>
            <li className="mb-1">Violates our Terms of Service or community guidelines</li>
            <li className="mb-1">Contains personal information of others without consent</li>
          </ul>

          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Content Review Process</h3>
          <ol className="list-decimal pl-6 mb-4 text-black">
            <li className="mb-1"><strong>Automated Screening</strong>: AI-powered content filtering</li>
            <li className="mb-1"><strong>User Reporting</strong>: Community-driven content flagging</li>
            <li className="mb-1"><strong>Manual Review</strong>: Human moderation for reported content</li>
            <li className="mb-1"><strong>Appeal Process</strong>: Users can appeal content removal decisions</li>
          </ol>

          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Content Removal</h3>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Immediate removal of clearly inappropriate content</li>
            <li className="mb-1">24-hour review period for borderline content</li>
            <li className="mb-1">User notification of content removal with explanation</li>
            <li className="mb-1">Appeal process available for disputed removals</li>
          </ul>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b border-gray-200 pb-2">Intellectual Property Protection</h2>
          
          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Copyright Protection</h3>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">All original content is protected by copyright</li>
            <li className="mb-1">Copyright notices displayed throughout the app</li>
            <li className="mb-1">DMCA compliance procedures in place</li>
            <li className="mb-1">Regular copyright audits and updates</li>
          </ul>

          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Trademark Protection</h3>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">"Mosaic AI Story Maker" trademark pending</li>
            <li className="mb-1">Logo and visual identity protection</li>
            <li className="mb-1">Monitoring for unauthorized use</li>
            <li className="mb-1">Enforcement actions as necessary</li>
          </ul>

          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Trade Secret Protection</h3>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">AI algorithms and prompts are trade secrets</li>
            <li className="mb-1">Source code access restricted to authorized personnel</li>
            <li className="mb-1">Confidentiality agreements with all team members</li>
            <li className="mb-1">Secure development and deployment practices</li>
          </ul>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b border-gray-200 pb-2">Third-Party Rights</h2>
          
          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Open Source Compliance</h3>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">All open source components properly licensed</li>
            <li className="mb-1">License compatibility verified</li>
            <li className="mb-1">Attribution requirements met</li>
            <li className="mb-1">Source code available as required</li>
          </ul>

          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Service Provider Rights</h3>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Clear agreements with all third-party services</li>
            <li className="mb-1">Data usage rights clearly defined</li>
            <li className="mb-1">Compliance with service provider terms</li>
            <li className="mb-1">Regular review of third-party relationships</li>
          </ul>

          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">API Rights</h3>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Proper licensing for all API services</li>
            <li className="mb-1">Rate limiting and usage compliance</li>
            <li className="mb-1">Data handling according to API terms</li>
            <li className="mb-1">Regular monitoring of API usage</li>
          </ul>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b border-gray-200 pb-2">Content Licensing</h2>
          
          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Inbound Licenses</h3>
          <p className="mb-2 text-black"><strong>Open Source Software</strong>:</p>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">MIT License: React Native, Expo SDK, Zustand</li>
            <li className="mb-1">Apache License 2.0: React, React Navigation</li>
            <li className="mb-1">BSD License: Node.js and related packages</li>
          </ul>
          <p className="mb-2 text-black"><strong>Third-Party Services</strong>:</p>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Stripe: Payment processing services</li>
            <li className="mb-1">OpenAI: AI story generation</li>
            <li className="mb-1">Google: Authentication and AI services</li>
            <li className="mb-1">Apple: Authentication services</li>
          </ul>

          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Outbound Licenses</h3>
          <p className="mb-2 text-black"><strong>User License</strong>:</p>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Limited, non-exclusive, non-transferable</li>
            <li className="mb-1">Personal use only</li>
            <li className="mb-1">No commercial distribution</li>
            <li className="mb-1">Revocable at any time</li>
          </ul>
          <p className="mb-2 text-black"><strong>Partner Licenses</strong>:</p>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Confidentiality agreements required</li>
            <li className="mb-1">Limited use for specific purposes</li>
            <li className="mb-1">Regular review and renewal</li>
            <li className="mb-1">Termination clauses included</li>
          </ul>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b border-gray-200 pb-2">Content Disputes</h2>
          
          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Dispute Resolution Process</h3>
          <ol className="list-decimal pl-6 mb-4 text-black">
            <li className="mb-1"><strong>Initial Contact</strong>: Direct communication with rights holder</li>
            <li className="mb-1"><strong>Documentation</strong>: Gather evidence and supporting materials</li>
            <li className="mb-1"><strong>Legal Review</strong>: Internal legal team assessment</li>
            <li className="mb-1"><strong>Resolution</strong>: Negotiated settlement or legal action</li>
            <li className="mb-1"><strong>Documentation</strong>: Record all decisions and actions</li>
          </ol>

          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">DMCA Compliance</h3>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Designated agent for copyright claims</li>
            <li className="mb-1">Proper notice and takedown procedures</li>
            <li className="mb-1">Counter-notification process</li>
            <li className="mb-1">Regular training on copyright law</li>
          </ul>

          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">International Considerations</h3>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Compliance with international copyright treaties</li>
            <li className="mb-1">Respect for local laws and regulations</li>
            <li className="mb-1">Cross-border content rights management</li>
            <li className="mb-1">Regular legal updates and compliance reviews</li>
          </ul>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b border-gray-200 pb-2">Content Security</h2>
          
          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Data Protection</h3>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Encryption of all stored content</li>
            <li className="mb-1">Secure transmission protocols</li>
            <li className="mb-1">Access controls and authentication</li>
            <li className="mb-1">Regular security audits</li>
          </ul>

          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Content Backup</h3>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Regular automated backups</li>
            <li className="mb-1">Secure off-site storage</li>
            <li className="mb-1">Disaster recovery procedures</li>
            <li className="mb-1">Content restoration capabilities</li>
          </ul>

          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Access Controls</h3>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Role-based access permissions</li>
            <li className="mb-1">Multi-factor authentication</li>
            <li className="mb-1">Regular access reviews</li>
            <li className="mb-1">Audit logging for all access</li>
          </ul>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b border-gray-200 pb-2">Content Updates and Maintenance</h2>
          
          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Regular Updates</h3>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Content library updates</li>
            <li className="mb-1">AI model improvements</li>
            <li className="mb-1">Security patches and updates</li>
            <li className="mb-1">Feature enhancements</li>
          </ul>

          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Content Archival</h3>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Inactive content archival</li>
            <li className="mb-1">Long-term storage solutions</li>
            <li className="mb-1">Content retrieval procedures</li>
            <li className="mb-1">Data retention policies</li>
          </ul>

          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Content Migration</h3>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Platform migration procedures</li>
            <li className="mb-1">Data format conversions</li>
            <li className="mb-1">Content integrity verification</li>
            <li className="mb-1">User notification processes</li>
          </ul>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b border-gray-200 pb-2">Contact Information</h2>
          
          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Content Rights Inquiries</h3>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1"><strong>Email</strong>: <a href="mailto:support@mosaicai.in" className="text-blue-600 hover:text-blue-800 underline">support@mosaicai.in</a></li>
            <li className="mb-1"><strong>Legal Department</strong>: <a href="mailto:support@mosaicai.in" className="text-blue-600 hover:text-blue-800 underline">support@mosaicai.in</a></li>
            <li className="mb-1"><strong>DMCA Agent</strong>: <a href="mailto:support@mosaicai.in" className="text-blue-600 hover:text-blue-800 underline">support@mosaicai.in</a></li>
            <li className="mb-1"><strong>Address</strong>: [Your Business Address]</li>
          </ul>

          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Response Time</h3>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">General inquiries: 3-5 business days</li>
            <li className="mb-1">DMCA claims: 24-48 hours</li>
            <li className="mb-1">Legal matters: 1-2 business days</li>
            <li className="mb-1">Emergency issues: Immediate response</li>
          </ul>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4 border-b border-gray-200 pb-2">Compliance and Monitoring</h2>
          
          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Regular Audits</h3>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Quarterly content rights audits</li>
            <li className="mb-1">Annual legal compliance reviews</li>
            <li className="mb-1">Ongoing monitoring of third-party licenses</li>
            <li className="mb-1">Regular training for team members</li>
          </ul>

          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Documentation</h3>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">All rights agreements documented</li>
            <li className="mb-1">Regular updates to rights database</li>
            <li className="mb-1">Clear audit trails for all decisions</li>
            <li className="mb-1">Comprehensive rights management system</li>
          </ul>

          <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">Training</h3>
          <ul className="list-disc pl-6 mb-4 text-black">
            <li className="mb-1">Regular training on intellectual property law</li>
            <li className="mb-1">Updates on new regulations and requirements</li>
            <li className="mb-1">Best practices for content management</li>
            <li className="mb-1">Emergency response procedures</li>
          </ul>

          <div className="border-t border-gray-200 pt-6 mt-8">
            <div className="text-center">
              <h3 className="text-lg font-semibold text-gray-900 mb-2">Mosaic AI Story Maker</h3>
              <p className="text-sm text-gray-600 mb-2 italic">Creating magical stories for children through AI technology</p>
              <p className="text-sm text-gray-600 font-semibold">Content Rights Information © 2025 Mosaic AI Story Maker. All rights reserved.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default ContentRights